### ISSUE TITLE
Travis builds are taking too long, and hence are failing

### ISSUE THREAD

**Issue by FrontierOtr** [ambiata/ivory#565]
Build time is regularaly exceeding 50 minutes, which is the cut off.

**Comment by charleso** [comment]
The culprit is `DatasetsSpec` and it's generators. I'm going to look at this first thing Monday.

**Comment by markhibberd** [comment]
I don't think it is specifically that test causing the issue, there is a bunch of memory pressure caused from over aggressive loading of stores. I think we should consider dropping the 'Store' on 'Snapshot' back to just a 'StoreId'. Whatever happens can you please _not_ tone down the test size or number of cases, it should be able to handle that in its sleep, and it is an issue with the prod code that it can't. If it is the travis build causing the issue, just delete it, we can start working in earnest on something more sane. If it is the slow jenkins build, we should have a look at the really slow IO test to give us a bit more breathing room.

**Comment by charleso** [comment]
When I hit it with `jstack` it was spinning in `Gen.flatMap` for that spec. There's something seriously pathological about them. From two of the Jenkins builds:

```
22:17:33 [info] Passed: Total 167, Failed 0, Errors 0, Passed 167, Pending 1
02:23:13 [info] DatasetsSpec
```

```
03:22:58 [info] Passed: Total 167, Failed 0, Errors 0, Passed 167, Pending 1
05:09:14 [info] DatasetsSpec
```

I'll let you know more when I look into it tomorrow.

**Comment by charleso** [comment]
> I don't think it is specifically that test causing the issue, there is a bunch of memory pressure caused from over aggressive loading of stores.

Although maybe that's what you mean. Hmm.

**Comment by markhibberd** [comment]
If it helps, here is the test times from a normal CI run, https://s3.amazonaws.com/uploads.hipchat.com/66910/467259/IpiDv4vtO7eQm1X/times.txt, regrettably this timing does not include the time it takes to run the `Gen`. The more I look at this, the more I think that the Snapshot data type is wrong, I think there needs to be a version that includes all the store factset ids, but not the partitions.

Note also that this test isn't new, and wasn't changed in the last commit, it just the one the shows up the issue from the slowdown.

**Comment by charleso** [comment]
Fixed (hopefully) in https://github.com/ambiata/ivory/pull/567
