### ISSUE TITLE
Slow test.

### ISSUE THREAD

**Issue by markhibberd** [ambiata/ivory#566]
IngestSpec, which runs for 6 minutes by itself:

```
[info] Total for specification IngestSpec
[info] Finished in 6 minutes 8 seconds, 852 ms
[info] 4 examples, 15 expectations, 0 failure, 0 error
```

Looks like this slow things down a lot on normal ci: https://github.com/ambiata/ivory/blob/master/ivory-operation/src/test/scala/com/ambiata/ivory/operation/ingestion/IngestSpec.scala#L27-L52

Running IO spec 100 times sequentially apparently not a good idea.

**Comment by raronson** [comment]
@charleso

**Comment by charleso** [comment]
Looks better, from 4m to 60ms.

https://ci.ambiata.com/job/ivory/493
